#url ??????? ????????
base.url=http://regard.ru

#???????
type.browser=chrome

#???? ? chtomdriver
<<<<<<< HEAD
path.chrome.driver.windows=src/main/resources/driver/chromedriver
=======
path.chrome.driver.windows=src/main/resources/driver/chromedriver.exe
>>>>>>> a2a1b5512e184cdb97a584116b88bb32530a4589

#????????? ??????? ????????
implicitly.wait=30
page.load.timeout=30